### ISSUE TITLE
Register e-NABLE for Github non-profit program

### ISSUE THREAD

**Issue by bryn-davis** [enable-medellin/admin#2]
This will allow us to take repositories private - with our current free account they are all visible to the public.  See [this link](https://github.com/nonprofit) for the required documentation.

The first couple of items on the list are
 * Github account name is `enable-medellin`
 * Github organization URL is https://github.com/enable-medellin

**Comment by bryn-davis** [comment]
@adamarmfield - I've shared a link to the required documentation for getting a non-profit Github account (which I think we want).  I've assigned this issue to @antoniavandunem for now, but it can easily be assigned to someone else.

(Tip - Using the @user-name format in a comment adds the person to the issue, so that they'll get e-mail notifications of discussion activity.  They can unsubscribe the notifications if they wish.)

**Comment by mark-walbran** [comment]
@bryn-davis  sounds like we may not need to do this actually.

As of Jan 2019 free accounts have access to unlimited private repositories according to TechCrunch:
https://techcrunch.com/2019/01/07/github-free-users-now-get-unlimited-private-repositories/.

We should decide which repositories and projects we want to make private in this case. I would suggest that a lot of them would be better this way during the development stage.

Perhaps only made public once completed.

**Comment by bryn-davis** [comment]
Looking at this a little more, we seem to have the "Github Team" plan, but discounted to $0 in perpetuity.  Here is a screenshot from our organization settings.

<img width="1043" alt="screen shot 2019-02-26 at 10 20 58 am" src="https://user-images.githubusercontent.com/18235959/53424094-8e8ad000-39b0-11e9-9816-f49a58a26a33.png">

I'm not exactly clear how we got this "coupon" but I may well have selected non-profit as an option when I created the `enable-medellin` organization.  Perhaps they're not bothering to verify non-profit status anymore and are simply taking our word.  Whatever the case, here's the description of the "Team" plan and the upgrade option ("Enterprise").  We really don't need any of the Enterprise features, and so I think we are probably all set here.

<img width="682" alt="screen shot 2019-02-26 at 10 19 54 am" src="https://user-images.githubusercontent.com/18235959/53424054-77e47900-39b0-11e9-8583-431f306c8971.png">

**Comment by bryn-davis** [comment]
Given that it looks like we can take our repositories private, I suggest we go ahead and do that.  Various aspects of our projects now show up readily in Google (e.g., try searching "enable medellin github issues").

I think it's painless to switch back and forth between private and public, and all our people who have joined Github should be able to see either just fine.  I propose I switch the `admin` repository to private and see what happens.  @mark-walbran - I'd like your go ahead before doing this.  Both to make sure you agree and so that you can do a quick spot check for problems after I make the change.

If that all works well, we'll take the other repositories private too.

**Comment by mark-walbran** [comment]
Sounds good Bryn.

Go ahead and notify me to check after it's done!

**Comment by antoniavandunem** [comment]
Hi Bryn, I sent an email to github on Thursday requesting to be a nonprofit so potentially it is that. Does that mean I don’t need to follow this up anymore ?

thanks

Sent from my iPhone

On 26 Feb 2019, at 10:26 am, Brynmor Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking at this a little more, we seem to have the "Github Team" plan, but discounted to $0 in perpetuity. Here is a screenshot from our organization settings.

[screen shot 2019-02-26 at 10 20 58 am]<https://user-images.githubusercontent.com/18235959/53424094-8e8ad000-39b0-11e9-9816-f49a58a26a33.png>

I'm not exactly clear how we got this "coupon" but I may well have selected non-profit as an option when I created the enable-medellin organization. Perhaps they're not bothering to verify non-profit status anymore and are simply taking our word. Whatever the case, here's the description of the "Team" plan and the upgrade option ("Enterprise"). We really don't need any of the Enterprise features, and so I think we are probably all set here.

[screen shot 2019-02-26 at 10 19 54 am]<https://user-images.githubusercontent.com/18235959/53424054-77e47900-39b0-11e9-8583-431f306c8971.png>

**Comment by bryn-davis** [comment]
Thanks @antoniavandunem - I'm sure they've just responded to your e-mail.  I think we are all done with this task - I'll close the issue.

@mark-walbran - It seems like Github allows private repos for individual users but is still monetizing the organization accounts (this makes sense).  Antonia has us sorted for the free non-profit account though.  I'll try making this repo private momentarily.
